site_name: Pydantic
site_description: Data validation and settings management using python 3.6 type hinting
strict: true

theme:
  name: 'material'
  palette:
    primary: pink
    accent: pink

repo_name: samuelcolvin/pydantic
repo_url: https://github.com/samuelcolvin/pydantic
google_analytics:
- 'UA-62733018-4'
- 'auto'

nav:
- Introduction: index.md
- install.md
- usage.md
- Contributing to Pydantic: contributing.md
- benchmarks.md
- Pycharm Plugin: pycharm_plugin.md
- Using Pydantic: using_pydantic.md
- Change Log: changelog.md

markdown_extensions:
- markdown.extensions.codehilite:
    guess_lang: false
- markdown_include.include:
    base_path: docs
- admonition
- codehilite
